version: 2
updates:
  # Java/Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "bernardo"
    assignees:
      - "bernardo"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      aws-sdk:
        patterns:
          - "software.amazon.awssdk:*"
          - "com.amazonaws:*"
        update-types:
          - "minor"
          - "patch"
      jackson:
        patterns:
          - "com.fasterxml.jackson.*:*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "org.junit.*:*"
          - "org.mockito:*"
          - "io.rest-assured:*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "thismakesmehappy"
    assignees:
      - "thismakesmehappy"
    commit-message:
      prefix: "ci"
      include: "scope"